name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: blacksmith-4vcpu-ubuntu-2404
            target: x64
          - image: blacksmith-6vcpu-macos-latest
            target: arm64
          - image: blacksmith-4vcpu-windows-2025
            target: x64
    runs-on: ${{ matrix.image }}
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          rust: stable
          rust-native: ${{ matrix.target }}
          tool-cargo-binstall: jabba(jabba-shim)=Pistonite/jabba-shim
      - uses: Pistonight/mono-dev/actions/permanent-cache@main
        with:
          path: | 
            .jabba
            .gradle-test-home
          key: gradle-wrapper-test
          version: v1
          task: --list
      - run: task check
      - run: task test
      - uses: Pistonight/mono-dev/actions/rust-xplat@main
        with:
          arch: ${{ matrix.target }}
          binary: gradlew
          
